# Generated by Django 5.2.4 on 2025-08-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeds', '0001_initial'),
        ('categories', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='breeds.breed')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='categories.category')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='farms.farm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
