# Generated by Django 5.2.4 on 2025-08-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='property',
            new_name='farm',
        ),
    ]
