# Generated by Django 5.2.4 on 2025-08-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_rename_property_animal_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='culling_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Baixa'),
        ),
        migrations.AddField(
            model_name='animal',
            name='culling_reason',
            field=models.CharField(blank=True, choices=[('VD', 'Venda'), ('MT', 'Morte')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
