# Generated by Django 5.2.4 on 2025-08-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        ('inseminations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_birth', models.DateField(blank=True, null=True)),
                ('expected_dry', models.DateField(blank=True, null=True)),
                ('dry', models.DateField(blank=True, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='births', to='animals.animal')),
                ('insemination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='births', to='inseminations.insemination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
