# Generated by Django 5.2.4 on 2025-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('births', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birth',
            name='birth_type',
            field=models.CharField(blank=True, choices=[('F', 'Fêmea'), ('M', 'Macho'), ('SF', 'Natimorto Fêmea'), ('SM', 'Natimorto Macho')], help_text='Sexo/condição do bezerro no parto', max_length=2, null=True, verbose_name='Tipo do nascimento'),
        ),
    ]
