# Generated by Django 5.2.4 on 2025-10-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_reproductive_female',
            field=models.BooleanField(default=False, help_text='Pode ser inseminada e ter partos', verbose_name='Fêmea reprodutiva'),
        ),
    ]
