# Generated by Django 5.2.4 on 2025-08-14 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insemination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_insemination', models.DateField()),
                ('expected_pregnancy', models.DateField(blank=True, null=True)),
                ('pregnancy_check', models.DateField(blank=True, null=True)),
                ('is_pregnant', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inseminations', to='animals.animal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
