# Generated by Django 5.2.4 on 2025-10-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inseminations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insemination',
            name='bull',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
